#!/usr/bin/env ruby
require File.expand_path(File.dirname(__FILE__) + "/../initialize")

begin
  sinatra_path = 'sinatra'
  require sinatra_path
rescue LoadError => e
  if e.message =~ /#{Regexp.escape(sinatra_path)}$/
    raise "sinatra not available. Install it with sudo gem install sinatra"
  else
    raise e
  end
end

set :sessions, true

get '/' do
  markup = <<-MARKUP
<p id="greeting">
  Whazzup!?
  <a href="/clicky_click">Click me</a>
</p>
  MARKUP
  if session['user'].nil?
    markup << <<-MARKUP
<form method="post" action="/login">
  <input type="text" id="login" name="login" />
  <input type="submit" id="submit_login" />
</form>
    MARKUP
  else
    markup << <<-MARKUP
<p id="session">Hello, #{session['user']}</p>
    MARKUP
  end

  markup
end
post '/login' do
  session['user'] = params['login']
  redirect '/'
end
get '/clicky_click' do
  "Booyah!"
end
